# call dein#recache_runtimepath() when removing a plugin

# ----- [dein] -----
[[plugins]]
repo = 'Shougo/dein.vim'


# ----- [Powerline] -----
#
# vim-airline を使用する場合は, 以下の方法で Ricty for Powerline をインストールする
#
# brew tap sanemat/font
# brew install ricty --with-powerline
# cp -f /usr/local/opt/ricty/share/fonts/Ricty*.ttf ~/Library/Fonts/
# fc-cache -vf
#
[[plugins]]
repo = 'vim-airline/vim-airline'
hock_add = '''
let g:airline_powerline_fonts = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'


# ----- [Terminal] -----
[[plugins]]
repo = 'kassio/neoterm'

# ----- [Filter] -----
# [[plugins]]
# repo = 'Shougo/unite.vim'

# [[plugins]]
# repo = 'Shougo/vimfilter.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'


# ----- [tags] -----
[[plugins]]
repo = 'vim-scripts/gtags.vim'

[[plugins]]
repo = 'jsfaint/gen_tags.vim'
hook_add = '''
    let g:gen_tags#gtags_auto_gen = 1
'''

# ----- [Git] -----
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

# ----- [edit] -----
[[plugins]]
repo = 'thinca/vim-qfreplace'

[[plugins]]
repo = 'Shougo/neocomplete.vim'


# ----- [colorscheme] -----
[[plugins]]
repo = 'noahfrederick/vim-hemisu'

[[plugins]]
repo = 'fcpg/vim-orbital'

[[plugins]]
repo = 'reedes/vim-colors-pencil'

[[plugins]]
repo = 'kamykn/dark-theme.vim'
